package edu.upenn.sam3d

import edu.upenn.sam3d.engine.EngineStager
import edu.upenn.sam3d.process.EngineRequirements
import java.nio.file.Files
import java.nio.file.Path
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * The install-time requirements rewrite. The behaviour under test is what unblocked a clean Windows
 * machine: no `git+` requirement may survive, because both pip and uv install those by shelling out
 * to a `git` executable that a fresh lab PC doesn't have.
 */
class EngineRequirementsTest {

    @Test
    fun `the segment-anything git URL becomes an https archive`() {
        val out = EngineRequirements.rewrite(
            listOf("numpy", "git+https://github.com/facebookresearch/segment-anything.git", "tqdm")
        )
        assertContains(out, EngineRequirements.SEGMENT_ANYTHING_ARCHIVE)
        assertTrue(out.none { it.trim().startsWith("git+") }, "no VCS requirement may survive: $out")
        assertTrue(out.containsAll(listOf("numpy", "tqdm")), "unrelated requirements are untouched")
    }

    @Test
    fun `any github git requirement is converted, including a pinned branch`() {
        val out = EngineRequirements.rewrite(listOf("git+https://github.com/org/repo.git@dev"))
        assertContains(out, "https://github.com/org/repo/archive/refs/heads/dev.zip")
    }

    @Test
    fun `build-only packages are commented out rather than installed`() {
        val out = EngineRequirements.rewrite(listOf("torch", "pyinstaller"))
        assertContains(out, "torch")
        assertTrue(out.none { it.trim() == "pyinstaller" }, "pyinstaller must not be installed: $out")
        assertTrue(out.any { it.startsWith("#") && it.contains("pyinstaller") }, "and the omission is explained")
    }

    @Test
    fun `version specifiers do not confuse the build-only match`() {
        val out = EngineRequirements.rewrite(listOf("pyinstaller==6.3.0", "numpy>=1.24", "Pillow"))
        assertTrue(out.none { it.trim().startsWith("pyinstaller") })
        assertContains(out, "numpy>=1.24")
        assertContains(out, "Pillow")
    }

    @Test
    fun `comments and blank lines survive the rewrite`() {
        val out = EngineRequirements.rewrite(listOf("# a note", "", "numpy"))
        assertEquals("# a note", out[0])
        assertEquals("", out[1])
        assertContains(out, "numpy")
    }

    @Test
    fun `extras are appended`() {
        val out = EngineRequirements.rewrite(listOf("numpy"), extras = listOf("PySide6"))
        assertContains(out, "PySide6")
    }

    /**
     * Guards the real file, not a fixture: if the vendored engine ever gains another VCS requirement,
     * this fails here rather than on a lab machine halfway through a PyTorch download.
     */
    @Test
    fun `the vendored requirements file installs with no git executable`() {
        val vendored = EngineStager.findInWorkingDirAncestors()?.resolve("requirements.txt")
        if (vendored == null || !Files.exists(vendored)) return  // packaged/CI checkout without pipeline/

        val out = EngineRequirements.rewrite(Files.readAllLines(vendored))
        val vcs = out.filter { line ->
            val t = line.trim()
            !t.startsWith("#") && (t.startsWith("git+") || t.startsWith("hg+") || t.startsWith("svn+"))
        }
        assertTrue(vcs.isEmpty(), "these still need a VCS client on the user's machine: $vcs")
        assertContains(out, EngineRequirements.SEGMENT_ANYTHING_ARCHIVE)
    }

    @Test
    fun `materialize writes a generated file with a provenance header`() {
        val dir = Files.createTempDirectory("reqs-test")
        try {
            val source = dir.resolve("requirements.txt")
            Files.write(source, listOf("numpy", "git+https://github.com/facebookresearch/segment-anything.git"))
            val dest: Path = EngineRequirements.materialize(source, dir.resolve("nested/out.txt"), listOf("PySide6"))

            val text = Files.readString(dest)
            assertTrue(text.startsWith("# Generated by SAM3D Desktop"), "header explains where this came from")
            assertContains(text, EngineRequirements.SEGMENT_ANYTHING_ARCHIVE)
            assertContains(text, "PySide6")
            assertFalse(text.lines().any { it.trim().startsWith("git+") })
        } finally {
            dir.toFile().deleteRecursively()
        }
    }
}
