package edu.upenn.sam3d.process

import java.nio.file.Files
import java.nio.file.Path

/**
 * Produces the requirements file *Set up environment* actually installs from, derived at runtime from
 * the engine's vendored `requirements.txt`.
 *
 * The vendored file is read-only (CLAUDE.md rule 1: never modify anything under `pipeline/`), but
 * installing it verbatim is broken on a clean machine for one specific reason:
 *
 * > `git+https://github.com/facebookresearch/segment-anything.git`
 *
 * Both pip and uv install a `git+` requirement by shelling out to the **`git` executable**. A fresh
 * Windows machine — the lab-PC case this was written for — has no Git, so the install dies partway
 * through with a "git not found" error, after the user has already waited through the PyTorch
 * download. Nothing in the app's "no terminal required" promise prepares them for installing Git.
 *
 * GitHub serves every repository as a source archive over plain HTTPS, and pip/uv install from an
 * archive URL with no VCS involved at all. Rewriting the one line to that URL fetches the *same
 * source* — the `git+` form was unpinned too, so it already meant "whatever the default branch is" —
 * and removes the hidden Git dependency entirely.
 *
 * The same pass drops build-only tooling that has no business in a runtime environment (see
 * [BUILD_ONLY]) and folds in [EnvironmentSetupManager.EXTRA_DEPS], so one file describes exactly
 * what gets installed and the log shows it.
 */
object EngineRequirements {

    /** The engine's SAM dependency, expressed as a VCS checkout that needs a `git` binary. */
    private const val SEGMENT_ANYTHING_GIT = "git+https://github.com/facebookresearch/segment-anything.git"

    /** The same source as an HTTPS archive — no `git` executable required to install it. */
    const val SEGMENT_ANYTHING_ARCHIVE =
        "https://github.com/facebookresearch/segment-anything/archive/refs/heads/main.zip"

    /**
     * Packages in the vendored requirements that are build- or server-only and are never imported on
     * the desktop app's CLI path. Installing them costs download time and adds failure surface (
     * `pyinstaller` in particular pulls a compiler toolchain on some platforms) for no benefit.
     */
    val BUILD_ONLY = setOf("pyinstaller", "flask")

    /**
     * Rewrite the vendored requirement [lines] into what we install, appending [extras].
     *
     * Pure and order-preserving so the generated file reads as a recognisable version of the original.
     * Comments and blank lines survive; a provenance header is added by [materialize], not here.
     */
    fun rewrite(lines: List<String>, extras: List<String> = emptyList()): List<String> {
        val out = mutableListOf<String>()
        for (line in lines) {
            val trimmed = line.trim()
            when {
                trimmed.isEmpty() || trimmed.startsWith("#") -> out += line

                trimmed.equals(SEGMENT_ANYTHING_GIT, ignoreCase = true) -> {
                    out += "# rewritten from `$SEGMENT_ANYTHING_GIT` so no `git` executable is needed"
                    out += SEGMENT_ANYTHING_ARCHIVE
                }

                // Any other GitHub `git+` requirement gets the same treatment, branch and all.
                trimmed.startsWith("git+https://github.com/", ignoreCase = true) ->
                    out += gitHubArchiveUrl(trimmed) ?: trimmed

                packageName(trimmed) in BUILD_ONLY ->
                    out += "# omitted (build-only, never imported by the pipeline): $trimmed"

                else -> out += line
            }
        }
        if (extras.isNotEmpty()) {
            out += ""
            out += "# added by SAM3D Desktop — imported by the engine but absent from requirements.txt"
            out += extras
        }
        return out
    }

    /**
     * Write the rewritten requirements next to the app's other state and return the path. [dest]'s
     * parent is created if needed; the file is overwritten each run so an app update can't leave a
     * stale copy behind.
     */
    fun materialize(source: Path, dest: Path, extras: List<String> = emptyList()): Path {
        val rewritten = rewrite(Files.readAllLines(source), extras)
        Files.createDirectories(dest.parent)
        val header = listOf(
            "# Generated by SAM3D Desktop from $source — do not edit.",
            "# The vendored requirements.txt is read-only; this derived copy replaces its `git+` URL",
            "# with an HTTPS archive so the install works on machines without Git installed.",
            "",
        )
        Files.write(dest, header + rewritten)
        return dest
    }

    /** `numpy==1.2` / `Pillow>=9` / `torch` → `numpy` / `pillow` / `torch`. Blank for non-package lines. */
    private fun packageName(requirement: String): String =
        requirement.substringBefore('#')
            .trim()
            .split('=', '<', '>', '!', '~', '[', ';', ' ')
            .first()
            .lowercase()

    /** `git+https://github.com/org/repo.git@ref` → the codeload archive URL for that ref. */
    private fun gitHubArchiveUrl(requirement: String): String? {
        val withoutScheme = requirement.removePrefix("git+").substringBefore('#')
        val ref = withoutScheme.substringAfter('@', "").ifBlank { "main" }
        val repo = withoutScheme.substringBefore('@').removeSuffix(".git").trimEnd('/')
        if (!repo.startsWith("https://github.com/")) return null
        // A bare ref could be a branch or a tag; `refs/heads/` covers the branch case the engine uses,
        // and a tag would need `refs/tags/`. Only the branch form appears in this pipeline.
        return "$repo/archive/refs/heads/$ref.zip"
    }
}
